name = "tulo-afrika"
main = "functions/api/[[path]].ts"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "tulo-afrika-db"
database_id = "YOUR_DATABASE_ID_HERE" # You'll get this after creating D1 database

# KV Namespace for sessions
[[kv_namespaces]]
binding = "SESSIONS"
id = "YOUR_KV_NAMESPACE_ID_HERE" # You'll get this after creating KV namespace

# Environment variables
[vars]
OPENROUTER_API_KEY = "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"
OPENROUTER_API_URL = "https://openrouter.ai/api/v1"

# Build configuration
[build]
command = "npm run build"

# Compatibility flags for Node.js APIs
compatibility_flags = ["nodejs_compat"]