name = "tulo-afrika"
main = "functions/api/[[path]].ts"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "tulo-afrika-db"
database_id = "475e676a-195d-4ab5-9ddc-c83f2cf37ac9"

# KV Namespace for sessions
[[kv_namespaces]]
binding = "SESSIONS"
id = "0a6c7569067047a9b141acbd7d3ea374"

# Environment variables
[vars]
OPENROUTER_API_KEY = "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"
OPENROUTER_API_URL = "https://openrouter.ai/api/v1"

# Build configuration
[build]
command = "npm run build"

# Compatibility flags for Node.js APIs
compatibility_flags = ["nodejs_compat"]