name = "tulo-afrika"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "tulo-db"
database_id = "78845220-9123-4a9d-a008-40ebfcd3d578"

# KV Namespace for sessions
[[kv_namespaces]]
binding = "SESSIONS"
id = "1e8b079621b243de93dbf55f43481395"

# Enable Cloudflare Workers AI
[ai]
binding = "AI"

# Environment variables should be set in Cloudflare Dashboard, not here
# Do not commit API keys to the repository