name = "tulo-afrika"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "tulo-afrika-db"
database_id = "475e676a-195d-4ab5-9ddc-c83f2cf37ac9"

# KV Namespace for sessions
[[kv_namespaces]]
binding = "SESSIONS"
id = "0a6c7569067047a9b141acbd7d3ea374"

# Environment variables should be set in Cloudflare Dashboard, not here
# Do not commit API keys to the repository